### ISSUE TITLE
[Feature request] add or() that takes other Result as argument

### ISSUE THREAD

**Issue by NekoiNemo** [kittinunf/Result#22]
Please consider adding the following function:

```
/**
 * Take this if it is [Result.Success] or [fallback] if this is [Result.Failure]
 */
infix fun <V : Any, E : Exception> Result<V, E>.or(fallback: Result<V, E>): Result<V, E> {
    return when (this) {
        is Result.Success -> this
        else -> fallback
    }
}

/**
 * Take this if it is [Result.Success] or calculate [fallback] if this is [Result.Failure]
 */
infix fun <V : Any, E : Exception> Result<V, E>.or(fallback: () -> Result<V, E>): Result<V, E> {
    return when (this) {
        is Result.Success -> this
        else -> fallback()
    }
}
```

As this is quite useful when your fallback has to be calculated as well, and implementation is too cumbersome to be implemented on the spot.

**Comment by kittinunf** [comment]
Hmm, it looks like you can already achieve it by using `flatMapError`?  Can you elaborate a bit more on why doesn't it suits your needs?

**Comment by NekoiNemo** [comment]
_To be honest, i kind of forgot about it when i submitted this request._ But as for "why" - mostly uniformity and readability. As something like
`val item = loadCache(url).or(download(url)).or(Placeholders.loadFailed)`
is far easier to understand at glance than
`val item = loadCache(url).flatMapError(download(url)).or(Placeholders.loadFailed)`

**Comment by kittinunf** [comment]
Maybe you can use import as to help you out. 

`import xxx.flatMapError as or`

I will close this issue as it has a way to get around it.
