### ISSUE TITLE
Publish library to maven central

### ISSUE THREAD

**Issue by uglyog** [kittinunf/Result#23]
Could you publish your library to maven central. It is causing issues for people who do not have jcenter setup.

See https://github.com/DiUS/pact-jvm/issues/521

**Comment by DanySK** [comment]
I second this request. This is also a blocker for kittinunf/fuel#747, as there's a dependency and hence loading fuel from Central results in:
```
Could not find com.github.kittinunf.result:result:2.2.0.
Searched in the following locations:
  - https://repo.maven.apache.org/maven2/com/github/kittinunf/result/result/2.2.0/result-2.2.0.pom
If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
Required by:
    project : > com.github.kittinunf.fuel:fuel:2.2.3

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

**Comment by DanySK** [comment]
@kittinunf let me know if you are going to publish this on Central, as alternatively I can repackage and publish under `org.danilopianini:result-kt`.

**Comment by kittinunf** [comment]
Ah I forgot about this! Please allow me to work on this, tonight 🙇

**Comment by DanySK** [comment]
Thanks @kittinunf, let me know if you need help!
