### ISSUE TITLE
[Idea] Suspending function support

### ISSUE THREAD

**Issue by a11n** [kittinunf/Result#27]
`Result` currently does not support [suspending functions](https://kotlinlang.org/docs/reference/coroutines.html#suspending-functions).

The following example won't compile:
```kotlin
suspend fun aSuspendingFunction() : Something

val result = Result.of { aSuspendingFunction() } //-> "Suspension functions can be called only within coroutine body"
```

Since `Result` is nice, for instance to work with web service calls, it would be very cool to support this new Kotlin feature right out of the box.

I'm currently using this workaround to work with `Result` in conjunction with coroutines:
```kotlin
val result = resultOf { aSuspendingFunction() }

private suspend fun <V : Any> resultOf(f: suspend () -> V): Result<V, Exception> = try {
    Success(f())
  } catch (e: Exception){
    Failure(e)
  }
```

What do you think? If  you like the idea I could prepare an according PR.

**Comment by a11n** [comment]
`Result.success()`, `Result.failure()` and `Result.fold()` are also not capable of suspending functions at the moment.

Currently working around with:
```kotlin
suspend fun <V : Any> Result<V, *>.successSuspend(f: suspend (V) -> Unit) {
  when(this){
    is Success -> f(this.value)
    else -> {}
  }
```

**Comment by tudorgk** [comment]
@a11n Check out #28.

**Comment by kittinunf** [comment]
I support the idea very much! 👍  👍

**Comment by kittinunf** [comment]
With the version 1.4.0, this issue should be closed as fixed :)
