### ISSUE TITLE
Multiplatform support?

### ISSUE THREAD

**Issue by thewoolleyman** [kittinunf/Result#29]
Would you be open to a PR to add [multiplatform support](http://kotlinlang.org/docs/reference/multiplatform.html) to this project?

**Comment by kittinunf** [comment]
I am up for the idea but I don't have plan for it for now 😢

**Comment by rjaros** [comment]
I would really like to use your library with my Kotlin/JS project. For now I've just copied your `Result.kt` file (with your copyright notice of course), but it would be great if you could publish Kotlin/JS artifacts. The sources seem to be 100% compatible.

**Comment by kittinunf** [comment]
Yes, I think it will start a new version on this to support multiplatform!

**Comment by kittinunf** [comment]
Now it is supported by version 5
