### ISSUE TITLE
Add support of result. isSuccess()

### ISSUE THREAD

**Issue by amatkivskiy** [kittinunf/Result#32]
Hi @kittinunf 

Thanks for an awesome library 👍 
It is really useful and that's why I even created Java version of it https://github.com/amatkivskiy/resultforjava .

There are multiple things that I found really useful when I was creating Java version of it:

- Pretty often (especially for unit tests) it is really handy to have a method called : `result.isSuccess()` to be able to easily check state of result. Example: https://github.com/amatkivskiy/ResultForJava/blob/develop/result/src/main/java/com/amatkivskiy/result/Result.java#L17

- Another useful  method can be : `result.isEmpty()` which return true if `result.component1() == null`. Example: https://github.com/amatkivskiy/ResultForJava/blob/develop/result/src/main/java/com/amatkivskiy/result/Result.java#L24

What do you think about this?
If this is ok, I can create a pull request with mentioned changes.

**Comment by amatkivskiy** [comment]
@kittinunf  Any updates on this?

**Comment by kittinunf** [comment]
To be completely honest with you, I am reluctant to add those 2 methods. The reasons for that are 

1. Keeping the number of methods slim. 
- I feel like I wanna prefer having the only one or two ways of doing things. Especially, the functionalities already exist in the library.

2. There is no apparent benefit of having `isSuccess()`
- It looks more like a personal choice where you do want to use `isSuccess()`. Currently, we can use `when`  and `success` | `failure` which I believe it is more than enough.

Please elaborate your use case why the current solution doesn't work for you. I would love to hear and potentially change mind if you can demonstrate the benefit.

**Comment by kittinunf** [comment]
Closing this as I believe that the current API is suitable enough. Feel free to re-open this if you want to discuss more.
