### ISSUE TITLE
Difference between Result and Arrow-kt library?

### ISSUE THREAD

**Issue by IgorGanapolsky** [kittinunf/Result#40]
Hi,
I have a quick question: Arrow-kt has Either (https://arrow-kt.io/docs/datatypes/either/).  It seems like it does what Result library does.  Can you tell me the benefit of using Result over Arrow?

Thanks a lot,
Igor

**Comment by bohsen** [comment]
The api of Result is way easier to understand. Arrow-kt is very abstract.
