### ISSUE TITLE
Artifact result-coroutines not found

### ISSUE THREAD

**Issue by WellingtonCosta** [kittinunf/Result#46]
Hi,

Firstly I would like to congratulate you for the awesome project!

I'm trying to use ```result-coroutines``` in my project, but Gradle cannot download the artifact. Any idea?

I have the following repositories: 

```
repositories {
    google()
    jcenter()
    maven { url "http://kotlin.bintray.com/kotlinx" }
}
```

**Comment by WellingtonCosta** [comment]
It is available on Jitpack repository.

```
maven { url 'https://jitpack.io' }
```

**Comment by kittinunf** [comment]
Hmm I think you should be able to get it from the jcenter itself.

Take a look here 

https://jcenter.bintray.com/com/github/kittinunf/result/result/2.0.0/

**Comment by ckle32** [comment]
Hi,

I had the same problem. With 
```
repositories {
    jcenter()
}
```
my IDE was able to resolve `com.github.kittinunf.result:result:2.1.0` but unable to resolve `com.github.kittinunf.result:result-coroutines:2.1.0`.

@WellingtonCosta Thanks for your solution:
> 
> The version `2.0.0` can be found at:
> 
> `maven { url "https://dl.bintray.com/kittinunf/maven" }`



@kittinunf Your suggested link contains only `result` but not `result-coroutines`:
> 
> Hmm I think you should be able to get it from the jcenter itself.
> 
> Take a look here
> 
> https://jcenter.bintray.com/com/github/kittinunf/result/result/2.0.0/

Please have a look at the following two links:
* [https://jcenter.bintray.com/com/github/kittinunf/result/](url) (contains only `result`)
* [https://dl.bintray.com/kittinunf/maven/com/github/kittinunf/result/](url) (contains both `result` and `result-coroutines`)

In addition, i would like to thank you for this and your `fuel` project.

**Comment by kittinunf** [comment]
OHHH! TRUE! 

I haven't realized this before at all (I am not a coroutine user myself). I don't know why it doesn't get synced up. I will check this problem out.

**Comment by rvazquezglez** [comment]
With [jfrog shutting down jcenter and bintray](https://www.infoq.com/news/2021/02/jfrog-jcenter-bintray-closure/). The fix doesn't apply anymore. Is there another repo that holds it?

**Comment by bohsen** [comment]
@rvazquezglez Is `SuspendableResult` still needed after #54 was merged? I just started using coroutines and haven't used `SuspendableResult`.
