### ISSUE TITLE
Can't find coroutines 2.1.0 on jcenter

### ISSUE THREAD

**Issue by jcayzac** [kittinunf/Result#53]
Hi,

`com.github.kittinunf.result:result-coroutines:2.1.0` doesn't exist on jcenter. I can only find version `2.0.0` on a mulesoft repo. Did you forget to publish it?

Thank you.

**Comment by ckle32** [comment]
Please have a look on issue #46.

**Comment by Rody66** [comment]
The same problem.

**Comment by kittinunf** [comment]
Apparently there's a problem during jcenter sync process internally. 

Solved!
