### ISSUE TITLE
Question: Proper usage of SuspendResult?

### ISSUE THREAD

**Issue by carterhudson** [kittinunf/Result#69]
I'm migrating away from using ArrowKt's `Either` type so I don't have such a large dependency for a single purpose. However, I'm struggling to find a purpose for `SuspendResult`. I'm using coroutines in my application with no issues just using `Result`. For instance, I've got:
```
managedLaunch {
    Try     //typealias for Result to prevent clashing
        .of(fetchProfessionsUseCase.execute())     //execute is suspending
        .apply {
            failure {    //chain failure clause
                requireState()
                    .copy(error = it)
                    .publish()
            }
        }
        .map(::prepareFetchedCategories)  //non-suspending method reference
        .map(::showCategories)  //non-suspending method reference
}
```
If I use `SuspendResult`, calling `.map` requires another `suspend` function, which I find a bit unnecessary. If I use a normal `Result`, I am free to call a `suspend` function like `execute()`, as long as we're inside a `CoroutineScope`, and use non-suspending functions in my `.map` calls. Am I missing something or using these constructs incorrectly?

Edit: Actually, my failure clause never gets triggered when I use a `suspendCoroutine` and `resumeWithException`, though `try`/`catch` blocks do catch the error, so I know it is thrown.

**Comment by kittinunf** [comment]
Yeah I agree. I think I have reached the point where SuspendResult is no longer relevant. It might have been in the past but now it is not. Thanks for using the library! We also have version 5+ which support KMM. :)
