### ISSUE TITLE
Provide an idiomatic way to flatten List<Result>

### ISSUE THREAD

**Issue by asarkar** [kittinunf/Result#80]
From https://github.com/kittinunf/fuel/issues/805:

It'd be nice to able to do the following:
1. Transform `List<Result<Foo, FuelError>>` into `Result<List<Foo>, FuelError>`. If any of the `Result`s is an error, the final `Result` is an error too, sort of an `AND`.
2.  Transform `List<Result<Foo, FuelError>>` into `Result<List<Foo>, FuelError>`.  If any of the `Result`s is a success, the final `Result` is a success too, sort of an `OR`.

**Comment by kittinunf** [comment]
Just to confirm, I think we have support for 1. already with `lift()`. I am not sure how useful the 2. nd case is though. Let's assume that we have 5 items in the list like so;

List<Result<...>>
1. Success
2. Failure
3. Success
4. Success
5. Success

When we "lift" this into Result<List<>>, what do we do to the 2nd (the failure one?)? Just ignore them?

**Comment by asarkar** [comment]
> what do we do to the 2nd (the failure one?)?

Provide an error handler fn perhaps, user can do whatever they want in there with the exception.

**Comment by kittinunf** [comment]
Then I think we might be able to expand the lift() functionality then?

**Comment by kittinunf** [comment]
Close with new version
