### ISSUE TITLE
Enforced nullability on get()'s return type

### ISSUE THREAD

**Issue by lopes-felipe** [kittinunf/Result#90]
I just migrated from `2.2.0` to the current latest version (`5.1.0`) and the main diference I saw was the nullable success, which I found just great!

But, one thing that I didn't get was the signature change on the `get()` method. Given that `Result.Success<V>`'s `V`  can now be a nullable type, why does the `Result`'s abstract `get()` has to have an "enforced" nullable return (`: V?`).

This feels somewhat counter intuitive to me, given that, even if I have a non-nullable `Result` value (e.g.`Result<String, Exception>`), its `get()` will always return a nullable one (`String?`), which just includes an (apparently) unnecessary complexity to handle the return.

Is there a particular reason for this design? Perhaps some use case that I'm not seeing right now? If no, I would like to propose a change removing this enforced nullability on `get()`'s return type: https://github.com/kittinunf/Result/pull/91

**Comment by kittinunf** [comment]
First of all thanks for using Result! The reason behind this is that it is just an overlooking from my part I think this is excellent.

**Comment by lopes-felipe** [comment]
Awesome @kittinunf! Thanks for taking some time to look into this, this change's gonna be really useful from our side! :D 

Do you have some sort of version publication schedule? No rush of curse, its just so I can organize myself for it.

Thank you again and best regards!

**Comment by kittinunf** [comment]
I found a couple of bugs and improvement that I wanna land into the next version. Would you mind wait a bit sir? I think I would love to add `mapBoth` into the Result as well. Since I seem to miss it in my first run.

**Comment by lopes-felipe** [comment]
Sure, absolutely no problem! In fact, we at Alice have been creating a few internal extension functions for `Result` as well, so if you want to, you could create a couple of issues and we would be glad to help you implement them as soon as possible! :D

**Comment by kittinunf** [comment]
@lopes-felipe more than welcome for that 👍

**Comment by kittinunf** [comment]
Just to make sure the new version should support this finally. Please report back if there is problem or anything.
